<?php

namespace App\Exports;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;

class PreconcepcionalExport implements FromCollection, WithHeadings, WithMapping
{
    public function __construct(private Collection $rows) {}

    public function collection()
    {
        return $this->rows;
    }

    public function headings(): array
    {
        return [
            'id',
            'no',
            'tipo_documento',
            'numero_identificacion',
            'apellido_1',
            'apellido_2',
            'nombre_1',
            'nombre_2',
            'fecha_nacimiento',
            'edad',
            'sexo',
            'regimen_afiliacion',
            'pertenencia_etnica',
            'grupo_poblacional',
            'departamento_residencia',
            'municipio_residencia',
            'zona',
            'etnia',
            'asentamiento',
            'telefono',
            'direccion',
            'nivel_educativo',
            'discapacidad',
            'mujer_cabeza_hogar',
            'ocupacion',
            'estado_civil',
            'control_tradicional',
            'gestante_renuente',
            'inasistente',
            'nombre_ips_primaria',
            'hipertension_personal',
            'diabetes_mellitus',
            'enfermedad_renal',
            'cardiopatias',
            'epilepsia',
            'enfermedades_autoinmunes',
            'trastornos_mentales',
            'cancer',
            'enfermedades_infecciosas_cronicas',
            'uso_permanente_medicamentos',
            'alergias',
            'edad_menarquia',
            'fecha_ultimo_periodo_mestrual',
            'numero_gestaciones_previas',
            'partos_vaginales',
            'cesareas',
            'abortos',
            'complicaciones_obstetricas_previas',
            'hipertension_familiar',
            'diabetes_familiar',
            'malformaciones_congenitas',
            'enfermedades_geneticas',
            'enfermedades_mentales_familia',
            'muerte_materna_familia',
            'inicio_vida_sexual',
            'numero_parejas_sexuales',
            'uso_actual_metodos_anticonceptivos',
            'antecedentes_its',
            'deseo_reproductivo',
            'consumo_tabaco',
            'consumo_alcohol',
            'consumo_sustancias_psicoactivas',
            'actividad_fisica',
            'alimentacion_saludable',
            'violencias',
            'peso',
            'talla',
            'imc',
            'riesgo_nutricional',
            'suplementacion_acido_folico',
            'tetanos',
            'influenza',
            'covid_19',
            'fecha_tamizaje_sifilis',
            'resultado_sifilis',
            'fecha_tamizaje_vih',
            'resultado_vih',
            'fecha_tamizaje_hepatitis_b',
            'resultado_hepatitis_b',
            'citologia',
            'tamizaje_salud_mental',
            'riesgo_preconcepcional',
            'consejeria_preconcepcional',
            'educacion_planificacion_familiar',
            'recomendaciones_nutricionales',
            'ordenes_medicas',
            'created_at',
            'updated_at',
        ];
    }

    public function map($r): array
    {
        // Fechas como string para evitar líos Excel/SQLServer
        $fmtDate = fn($v) => $v ? (is_string($v) ? substr($v, 0, 10) : optional($v)->format('Y-m-d')) : null;
        $fmtDT   = fn($v) => $v ? (is_string($v) ? $v : optional($v)->format('Y-m-d H:i:s')) : null;

        return [
            $r->id,
            $r->no,
            $r->tipo_documento,
            $r->numero_identificacion,
            $r->apellido_1,
            $r->apellido_2,
            $r->nombre_1,
            $r->nombre_2,
            $fmtDate($r->fecha_nacimiento),
            $r->edad,
            $r->sexo,
            $r->regimen_afiliacion,
            $r->pertenencia_etnica,
            $r->grupo_poblacional,
            $r->departamento_residencia,
            $r->municipio_residencia,
            $r->zona,
            $r->etnia,
            $r->asentamiento,
            $r->telefono,
            $r->direccion,
            $r->nivel_educativo,
            $r->discapacidad,
            $r->mujer_cabeza_hogar,
            $r->ocupacion,
            $r->estado_civil,
            $r->control_tradicional,
            $r->gestante_renuente,
            $r->inasistente,
            $r->nombre_ips_primaria,
            $r->hipertension_personal,
            $r->diabetes_mellitus,
            $r->enfermedad_renal,
            $r->cardiopatias,
            $r->epilepsia,
            $r->enfermedades_autoinmunes,
            $r->trastornos_mentales,
            $r->cancer,
            $r->enfermedades_infecciosas_cronicas,
            $r->uso_permanente_medicamentos,
            $r->alergias,
            $r->edad_menarquia,
            $fmtDate($r->fecha_ultimo_periodo_mestrual),
            $r->numero_gestaciones_previas,
            $r->partos_vaginales,
            $r->cesareas,
            $r->abortos,
            $r->complicaciones_obstetricas_previas,
            $r->hipertension_familiar,
            $r->diabetes_familiar,
            $r->malformaciones_congenitas,
            $r->enfermedades_geneticas,
            $r->enfermedades_mentales_familia,
            $r->muerte_materna_familia,
            $r->inicio_vida_sexual,
            $r->numero_parejas_sexuales,
            $r->uso_actual_metodos_anticonceptivos,
            $r->antecedentes_its,
            $r->deseo_reproductivo,
            $r->consumo_tabaco,
            $r->consumo_alcohol,
            $r->consumo_sustancias_psicoactivas,
            $r->actividad_fisica,
            $r->alimentacion_saludable,
            $r->violencias,
            $r->peso,
            $r->talla,
            $r->imc,
            $r->riesgo_nutricional,
            $r->suplementacion_acido_folico,
            $r->tetanos,
            $r->influenza,
            $r->covid_19,
            $fmtDate($r->fecha_tamizaje_sifilis),
            $r->resultado_sifilis,
            $fmtDate($r->fecha_tamizaje_vih),
            $r->resultado_vih,
            $fmtDate($r->fecha_tamizaje_hepatitis_b),
            $r->resultado_hepatitis_b,
            $r->citologia,
            $r->tamizaje_salud_mental,
            $r->riesgo_preconcepcional,
            $r->consejeria_preconcepcional,
            $r->educacion_planificacion_familiar,
            $r->recomendaciones_nutricionales,
            $r->ordenes_medicas,
            $fmtDT($r->created_at),
            $fmtDT($r->updated_at),
        ];
    }
}
