<?php

return [
    'super_admin_id' => (int) env('SUPER_ADMIN_ID', 33),

    'module_permissions' => [
        [
            'code' => 'gestantes.access',
            'name' => 'Gestantes',
            'description' => 'Acceso al modulo Gestantes (preconcepcional, cargues y seguimiento).',
            'assignable' => true,
        ],
        [
            'code' => 'pai.access',
            'name' => 'Registro Diario PAI',
            'description' => 'Acceso al modulo de cargue y gestion PAI.',
            'assignable' => true,
        ],
        [
            'code' => 'nutricional.access',
            'name' => 'Alteraciones Nutricionales',
            'description' => 'Acceso a los modulos de alteraciones nutricionales (113/412/114).',
            'assignable' => true,
        ],
        [
            'code' => 'tamizajes.access',
            'name' => 'Tamizajes',
            'description' => 'Acceso al modulo de cargue y consulta de tamizajes.',
            'assignable' => true,
        ],
        [
            'code' => 'ciclosvida.access',
            'name' => 'Cursos de vida',
            'description' => 'Acceso al modulo de cursos de vida y sus submodulos PI.',
            'assignable' => true,
        ],
        [
            'code' => 'permissions.manage',
            'name' => 'Gestion de permisos',
            'description' => 'Permite administrar permisos y solicitudes de acceso.',
            'assignable' => false,
        ],
    ],

    'route_permission_map' => [
        'pai.access' => [
            'afiliado',
            'afiliado/*',
            'import-excel_2',
            'import-excel_2/*',
            'vacunas',
            'vacunas/*',
            'export-vacunas',
            'export-vacunas/*',
            'batch-verifications/*',
            'import/start',
            'import/status/*',
        ],
        'nutricional.access' => [
            'sivigila',
            'sivigila/*',
            'sivigila114',
            'sivigila114/*',
            'revision',
            'revision/*',
            'Seguimiento',
            'Seguimiento/*',
            'seguimiento_ocasional',
            'seguimiento_ocasional/*',
            'new412',
            'new412/*',
            'new412_seguimiento',
            'new412_seguimiento/*',
            'new412_seguimiento-data',
            'import-excel',
            'import-excel/*',
            'grafica-barras',
            'grafica-barras/*',
            'grafica-torta-clasificacion',
            'seguimientos/inteligencia',
            'report',
            'report1',
            'report2',
            'report3',
            'report4',
            'report5',
            'report6',
            'report7',
        ],
        'gestantes.access' => [
            'gestantes',
            'gestantes/*',
            'preconcepcional',
            'preconcepcional/*',
            'maestrosiv549',
            'maestrosiv549/*',
            'seguimientos1ges',
            'seguimientos1ges/*',
            'asignaciones*',
            'estadisticas/gestantes',
            'estadisticas/gestantes/*',
            'alertas',
            'alertas/*',
            'formatos/descargar',
            'ges_tipo1/*',
        ],
        'tamizajes.access' => [
            'excel-import',
            'excel-import/*',
            'tamizajes',
            'tamizajes/*',
            'descargar-formato1',
        ],
        'ciclosvida.access' => [
            'ciclos-vida',
            'ciclos-vida/*',
            'pi/*',
        ],
    ],

    'ges_allowed_patterns' => [
        'home',
        'home/*',
        'workspace',
        'workspace/*',
        'profile',
        'profile/*',
        'logout',
        'novedades',
        'novedades/*',
        'ui/mode-tabs',
        'download-pdf',
        'access/*',
        'gestantes',
        'gestantes/*',
        'preconcepcional',
        'preconcepcional/*',
        'maestrosiv549',
        'maestrosiv549/*',
        'seguimientos1ges',
        'seguimientos1ges/*',
        'asignaciones*',
        'estadisticas/gestantes',
        'estadisticas/gestantes/*',
        'alertas',
        'alertas/*',
        'formatos/descargar',
        'ges_tipo1/*',
    ],

    'request_recipients' => array_values(array_filter(array_map(
        static fn ($value) => trim((string) $value),
        explode(',', (string) env('ACCESS_REQUEST_RECIPIENTS', ''))
    ))),
];
