<?php

return [
    'source_connection' => env('CICLO_VIDA_SOURCE_CONNECTION', 'sqlsrv_1'),

    'sql_base_path' => env(
        'CICLO_VIDA_SQL_BASE_PATH',
        'C:\\Users\\jsuarez\\Documents\\UNIDAD COMPARTIDA\\JUAN  CAMILO\\POR ETAPAS\\SCRIPS\\LOS QUE SE USARON'
    ),

    'courses' => [
        'primera_infancia' => [
            'slug' => 'primera-infancia',
            'label' => 'Primera infancia',
            'menu_route' => 'ciclosvida.pi.menu',
            'description' => 'Desde los 8 dias hasta los 5 anos, 11 meses y 29 dias.',
            'age_label' => '8 dias a 5 anos, 11 meses y 29 dias',
            'color' => 'bg-primary',
            'icon' => 'fas fa-baby',
            'refresh' => ['days' => 120],
            'groups' => [
                [
                    'title' => 'Atenciones principales',
                    'icon' => 'fas fa-stethoscope',
                    'items' => ['medica', 'enfermeria'],
                ],
                [
                    'title' => 'Salud bucal',
                    'icon' => 'fas fa-tooth',
                    'header_route' => 'pi.bucal.index',
                    'items' => ['odontologia_general', 'fluor', 'placa', 'sellantes'],
                ],
                [
                    'title' => 'Tamizaje y micronutrientes',
                    'icon' => 'fas fa-vial',
                    'header_route' => 'pi.nutri.index',
                    'items' => ['hemoglobina', 'lactancia', 'vitamina_a', 'hierro', 'alertas'],
                ],
            ],
            'modules' => [
                'medica' => [
                    'label' => 'Atencion en salud medica',
                    'short_label' => 'Medica',
                    'description' => 'Consulta general, crecimiento y desarrollo.',
                    'icon' => 'fas fa-user-md',
                    'theme' => 'grad-indigo',
                    'route' => 'ciclosvida.show',
                    'route_params' => ['slug' => 'primera-infancia'],
                    'cache_module_key' => 'medica',
                    'record_type' => 'event',
                    'sql_file' => 'MEDICINA2.sql',
                    'materialized' => true,
                ],
                'enfermeria' => [
                    'label' => 'Atencion por enfermeria',
                    'short_label' => 'Enfermeria',
                    'description' => 'Procedimientos y seguimientos.',
                    'icon' => 'fas fa-notes-medical',
                    'theme' => 'grad-pink',
                    'route' => 'ciclosvida.enfermeria',
                    'cache_module_key' => 'enfermeria',
                    'record_type' => 'event',
                    'sql_file' => 'ENFERMERIA2.sql',
                    'materialized' => true,
                ],
                'odontologia_general' => [
                    'label' => 'Atencion en salud bucal',
                    'short_label' => 'Bucal',
                    'description' => 'Consulta odontologica general.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-sky',
                    'route' => 'pi.bucal.index',
                    'cache_module_key' => 'odontologia_general',
                    'record_type' => 'event',
                    'sql_file' => 'ODONTOLOGIA2.sql',
                    'materialized' => true,
                ],
                'fluor' => [
                    'label' => 'Fluor · 1er semestre (>=5 anos) · 2/al ano',
                    'short_label' => 'Fluor',
                    'description' => 'Topificacion de fluor en barniz.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-cyan',
                    'route' => 'pi.bucal.fluor.sem1',
                    'cache_module_key' => 'fluor',
                    'record_type' => 'event',
                    'sql_file' => 'FLUOR2.sql',
                    'materialized' => true,
                ],
                'placa' => [
                    'label' => 'Control de placa · 1er semestre (>=5)',
                    'short_label' => 'Placa',
                    'description' => 'Control de placa dental.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-emerald',
                    'route' => 'pi.bucal.placa.sem1',
                    'cache_module_key' => 'placa',
                    'record_type' => 'event',
                    'sql_file' => 'PLACA2.sql',
                    'materialized' => true,
                ],
                'sellantes' => [
                    'label' => 'Sellantes (>=3 anos · segun criterio)',
                    'short_label' => 'Sellantes',
                    'description' => 'Aplicacion de sellantes.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-amber',
                    'route' => 'pi.bucal.sellantes',
                    'cache_module_key' => 'sellantes',
                    'record_type' => 'event',
                    'sql_file' => 'SELLANTE2.sql',
                    'source' => [
                        'type' => 'view',
                        'table' => 'PRUEBA_DESNUTRICION.dbo.vw_bucal_sellantes as V',
                        'date_column' => 'V.fechaAtencion',
                    ],
                    'materialized' => true,
                ],
                'hemoglobina' => [
                    'label' => 'Tamizaje de hemoglobina',
                    'short_label' => 'Hemoglobina',
                    'description' => 'Tamizaje nominal por procedimiento.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-lime',
                    'route' => 'pi.nutri.hemoglobina',
                    'cache_module_key' => 'hemoglobina',
                    'record_type' => 'event',
                    'sql_file' => 'HEMOGLOBINA2.sql',
                    'source' => [
                        'type' => 'view',
                        'table' => 'PRUEBA_DESNUTRICION.dbo.vw_nutri_hemoglobina as V',
                        'date_column' => 'V.fechaAtencion',
                        'filters' => [
                            ['type' => 'between', 'column' => 'V.edadMeses', 'from' => 6, 'to' => 23],
                        ],
                    ],
                    'materialized' => true,
                ],
                'lactancia' => [
                    'label' => 'Lactancia materna R202 (1-8 meses)',
                    'short_label' => 'Lactancia',
                    'description' => 'Atencion para la promocion y apoyo a la lactancia materna.',
                    'icon' => 'fas fa-baby',
                    'theme' => 'grad-rose',
                    'route' => 'pi.nutri.lactancia',
                    'cache_module_key' => 'lactancia',
                    'record_type' => 'event',
                    'sql_file' => 'LACTANCIA MATERNA.sql',
                    'source' => [
                        'type' => 'function',
                        'name' => 'fn_pi_lactancia',
                    ],
                    'materialized' => true,
                ],
                'vitamina_a' => [
                    'label' => 'Vitamina A (24-60 meses) R202',
                    'short_label' => 'Vitamina A',
                    'description' => 'Suministro de vitamina A.',
                    'icon' => 'fas fa-capsules',
                    'theme' => 'grad-violet',
                    'route' => 'pi.nutri.vitamina_a',
                    'cache_module_key' => 'vitamina_a',
                    'record_type' => 'event',
                    'sql_file' => 'VITAMINA A.sql',
                    'source' => [
                        'type' => 'function',
                        'name' => 'fn_pi_vitamina_a',
                    ],
                    'materialized' => true,
                ],
                'hierro' => [
                    'label' => 'Hierro (24-59 meses) R202',
                    'short_label' => 'Hierro',
                    'description' => 'Suministro de hierro.',
                    'icon' => 'fas fa-pills',
                    'theme' => 'grad-orange',
                    'route' => 'pi.nutri.hierro',
                    'cache_module_key' => 'hierro',
                    'record_type' => 'event',
                    'sql_file' => 'HIERRO.sql',
                    'source' => [
                        'type' => 'view',
                        'table' => 'PRUEBA_DESNUTRICION.dbo.v_pi_hierro',
                        'date_column' => 'fechaConsulta',
                    ],
                    'materialized' => true,
                ],
                'alertas' => [
                    'label' => 'Alertas',
                    'short_label' => 'Alertas',
                    'description' => 'Pacientes sin atenciones segun regla.',
                    'icon' => 'fas fa-bell',
                    'theme' => 'grad-orange',
                    'route' => 'pi.alertas',
                    'cache_module_key' => 'alertas',
                    'record_type' => 'alert',
                    'sql_file' => 'NO_TIENEN ATENCION 3.sql',
                    'source' => [
                        'type' => 'function',
                        'name' => 'fn_pi_alertas',
                    ],
                    'materialized' => true,
                ],
                'datos_generales' => [
                    'label' => 'Datos generales',
                    'short_label' => 'Datos generales',
                    'description' => 'Resumen consolidado por curso de vida.',
                    'icon' => 'fas fa-notes-medical',
                    'theme' => 'grad-indigo',
                    'route' => 'pi.datos',
                    'materialized' => false,
                ],
            ],
        ],
        'infancia' => [
            'slug' => 'infancia',
            'label' => 'Infancia',
            'menu_route' => 'ciclosvida.infancia.menu',
            'description' => 'De 6 a 11 anos. Valoracion integral, proteccion especifica y seguimiento de atenciones por edad.',
            'age_label' => '6 a 11 anos',
            'color' => 'bg-success',
            'icon' => 'fas fa-child',
            'refresh' => ['days' => 120],
            'groups' => [
                [
                    'title' => 'Valoracion integral',
                    'icon' => 'fas fa-stethoscope',
                    'items' => ['medica', 'enfermeria', 'salud_bucal'],
                ],
                [
                    'title' => 'Proteccion especifica',
                    'icon' => 'fas fa-shield-heart',
                    'items' => ['fluor', 'placa', 'sellantes', 'hemoglobina', 'hematocrito'],
                ],
                [
                    'title' => 'Gestion del riesgo',
                    'icon' => 'fas fa-clipboard-check',
                    'items' => ['alertas'],
                ],
            ],
            'modules' => [
                'medica' => [
                    'label' => 'Atencion en salud medica',
                    'short_label' => 'Medica',
                    'description' => 'Valoracion integral en edades trazadoras de 6, 8 y 10 anos.',
                    'icon' => 'fas fa-user-md',
                    'theme' => 'grad-indigo',
                    'cache_module_key' => 'medica',
                    'record_type' => 'event',
                    'sql_file' => 'MEDICINA.sql',
                    'filters' => [
                        'age_year_min' => 6,
                        'age_year_max' => 11,
                    ],
                    'materialized' => true,
                ],
                'enfermeria' => [
                    'label' => 'Atencion por enfermeria',
                    'short_label' => 'Enfermeria',
                    'description' => 'Valoracion y seguimiento en edades trazadoras de 7, 9 y 11 anos.',
                    'icon' => 'fas fa-notes-medical',
                    'theme' => 'grad-pink',
                    'cache_module_key' => 'enfermeria',
                    'record_type' => 'event',
                    'sql_file' => 'ENFERMERIA.sql',
                    'filters' => [
                        'age_year_min' => 6,
                        'age_year_max' => 11,
                    ],
                    'materialized' => true,
                ],
                'salud_bucal' => [
                    'label' => 'Atencion en salud bucal',
                    'short_label' => 'Bucal',
                    'description' => 'Consulta odontologica general, al menos una vez al ano.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-sky',
                    'cache_module_key' => 'salud_bucal',
                    'record_type' => 'event',
                    'sql_file' => 'ODONTOLOGIA.sql',
                    'filters' => [
                        'age_year_min' => 6,
                        'age_year_max' => 11,
                    ],
                    'materialized' => true,
                ],
                'fluor' => [
                    'label' => 'Fluor',
                    'short_label' => 'Fluor',
                    'description' => 'Aplicacion de fluor. La frecuencia se analiza segun el rango de fechas elegido.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-cyan',
                    'cache_module_key' => 'fluor',
                    'record_type' => 'event',
                    'sql_file' => 'FLUOR.sql',
                    'filters' => [
                        'age_year_min' => 6,
                        'age_year_max' => 11,
                    ],
                    'materialized' => true,
                ],
                'placa' => [
                    'label' => 'Placa',
                    'short_label' => 'Placa',
                    'description' => 'Control de placa dental. La frecuencia se analiza segun el rango de fechas elegido.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'placa',
                    'record_type' => 'event',
                    'sql_file' => 'PLACA.sql',
                    'filters' => [
                        'age_year_min' => 6,
                        'age_year_max' => 11,
                    ],
                    'materialized' => true,
                ],
                'sellantes' => [
                    'label' => 'Sellante segun necesidad',
                    'short_label' => 'Sellantes',
                    'description' => 'Aplicacion de sellantes segun criterio clinico.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-amber',
                    'cache_module_key' => 'sellantes',
                    'record_type' => 'event',
                    'sql_file' => 'SELLANTE.sql',
                    'filters' => [
                        'age_year_min' => 6,
                        'age_year_max' => 11,
                    ],
                    'materialized' => true,
                ],
                'hemoglobina' => [
                    'label' => 'Tamizaje de hemoglobina',
                    'short_label' => 'Hemoglobina',
                    'description' => 'Tamizaje de hemoglobina en poblacion objetivo del curso.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-rose',
                    'cache_module_key' => 'hemoglobina',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE DE HEMOGLOBINA.sql',
                    'filters' => [
                        'age_year_min' => 10,
                        'age_year_max' => 11,
                    ],
                    'materialized' => true,
                ],
                'hematocrito' => [
                    'label' => 'Tamizaje de hematocrito',
                    'short_label' => 'Hematocrito',
                    'description' => 'Tamizaje de hematocrito en poblacion objetivo del curso.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-violet',
                    'cache_module_key' => 'hematocrito',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE DE HEMATOCRITO.sql',
                    'filters' => [
                        'age_year_min' => 10,
                        'age_year_max' => 11,
                    ],
                    'materialized' => true,
                ],
                'alertas' => [
                    'label' => 'Alertas',
                    'short_label' => 'Alertas',
                    'description' => 'Pacientes con atenciones pendientes segun la matriz operativa de infancia.',
                    'icon' => 'fas fa-bell',
                    'theme' => 'grad-orange',
                    'route' => 'ciclosvida.module.info',
                    'route_params' => ['slug' => 'infancia', 'moduleKey' => 'alertas'],
                    'record_type' => 'alert',
                    'materialized' => false,
                ],
                'datos_generales' => [
                    'label' => 'Datos generales',
                    'short_label' => 'Datos generales',
                    'description' => 'Resumen operativo del curso de vida y consolidado por modulo.',
                    'icon' => 'fas fa-chart-bar',
                    'theme' => 'grad-violet',
                    'route' => 'ciclosvida.module.info',
                    'route_params' => ['slug' => 'infancia', 'moduleKey' => 'datos_generales'],
                    'materialized' => false,
                ],
            ],
        ],
        'adolescencia' => [
            'slug' => 'adolescencia',
            'label' => 'Adolescencia',
            'menu_route' => 'ciclosvida.adolescencia.menu',
            'description' => 'De 12 a 17 anos. Prioriza salud mental, salud sexual y reproductiva y riesgo nutricional.',
            'age_label' => '12 a 17 anos',
            'color' => 'bg-info',
            'icon' => 'fas fa-user-friends',
            'refresh' => ['days' => 120],
            'groups' => [
                [
                    'title' => 'Atenciones integrales',
                    'icon' => 'fas fa-stethoscope',
                    'items' => ['medica', 'enfermeria'],
                ],
                [
                    'title' => 'Salud bucal y proteccion',
                    'icon' => 'fas fa-tooth',
                    'items' => ['salud_bucal', 'fluor', 'placa', 'sellantes', 'detartraje'],
                ],
                [
                    'title' => 'Salud sexual y reproductiva',
                    'icon' => 'fas fa-venus-mars',
                    'items' => ['asesoria_anticoncepcion', 'planificacion_r202', 'prueba_treponemica', 'prueba_rapida_vih'],
                ],
                [
                    'title' => 'Tamizajes',
                    'icon' => 'fas fa-vial',
                    'items' => ['hemoglobina', 'hematocrito'],
                ],
                [
                    'title' => 'Gestion del riesgo',
                    'icon' => 'fas fa-clipboard-check',
                    'items' => ['alertas'],
                ],
            ],
            'modules' => [
                'medica' => [
                    'label' => 'Atencion en salud medica',
                    'short_label' => 'Medica',
                    'description' => 'Consulta medica en edades trazadoras de 12, 14 y 16 anos.',
                    'icon' => 'fas fa-user-md',
                    'theme' => 'grad-indigo',
                    'cache_module_key' => 'medica',
                    'record_type' => 'event',
                    'sql_file' => 'MEDICINA.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 17,
                    ],
                    'materialized' => true,
                ],
                'enfermeria' => [
                    'label' => 'Atencion por enfermeria',
                    'short_label' => 'Enfermeria',
                    'description' => 'Consulta por enfermeria en edades trazadoras de 13, 15 y 17 anos.',
                    'icon' => 'fas fa-notes-medical',
                    'theme' => 'grad-pink',
                    'cache_module_key' => 'enfermeria',
                    'record_type' => 'event',
                    'sql_file' => 'ENFERMERIA.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 17,
                    ],
                    'materialized' => true,
                ],
                'salud_bucal' => [
                    'label' => 'Atencion en salud bucal',
                    'short_label' => 'Bucal',
                    'description' => 'Atencion en salud bucal al menos una vez al ano.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-sky',
                    'cache_module_key' => 'salud_bucal',
                    'record_type' => 'event',
                    'sql_file' => 'ODONTOLOGIA.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 17,
                    ],
                    'materialized' => true,
                ],
                'fluor' => [
                    'label' => 'Fluor',
                    'short_label' => 'Fluor',
                    'description' => 'Aplicacion de fluor segun el rango de fechas elegido.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-cyan',
                    'cache_module_key' => 'fluor',
                    'record_type' => 'event',
                    'sql_file' => 'FLUOR.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 17,
                    ],
                    'materialized' => true,
                ],
                'placa' => [
                    'label' => 'Control de placa',
                    'short_label' => 'Placa',
                    'description' => 'Control de placa dental segun el rango de fechas elegido.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'placa',
                    'record_type' => 'event',
                    'sql_file' => 'PLACA.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 17,
                    ],
                    'materialized' => true,
                ],
                'sellantes' => [
                    'label' => 'Sellante',
                    'short_label' => 'Sellante',
                    'description' => 'Aplicacion de sellantes segun necesidad.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-amber',
                    'cache_module_key' => 'sellantes',
                    'record_type' => 'event',
                    'sql_file' => 'SELLANTE.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 17,
                    ],
                    'materialized' => true,
                ],
                'detartraje' => [
                    'label' => 'Detartraje',
                    'short_label' => 'Detartraje',
                    'description' => 'Detartraje segun necesidad.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-orange',
                    'cache_module_key' => 'detartraje',
                    'record_type' => 'event',
                    'sql_file' => 'DETARTRAJE.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 17,
                    ],
                    'materialized' => true,
                ],
                'asesoria_anticoncepcion' => [
                    'label' => 'Asesoria en anticoncepcion',
                    'short_label' => 'Anticoncepcion',
                    'description' => 'Asesoria en anticoncepcion segun necesidad.',
                    'icon' => 'fas fa-venus-mars',
                    'theme' => 'grad-rose',
                    'cache_module_key' => 'asesoria_anticoncepcion',
                    'record_type' => 'event',
                    'sql_file' => 'ASESORIA ANTICONCEPCION.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 17,
                    ],
                    'materialized' => true,
                ],
                'planificacion_r202' => [
                    'label' => 'Metodo de planificacion R202',
                    'short_label' => 'Planificacion R202',
                    'description' => 'Suministro o seguimiento del metodo de planificacion en R202.',
                    'icon' => 'fas fa-notes-medical',
                    'theme' => 'grad-violet',
                    'cache_module_key' => 'planificacion_r202',
                    'record_type' => 'event',
                    'sql_file' => 'PLANIFICACION_FAMILIAR_202.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 17,
                    ],
                    'materialized' => true,
                ],
                'prueba_treponemica' => [
                    'label' => 'Prueba treponemica',
                    'short_label' => 'Treponemica',
                    'description' => 'Prueba treponemica segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'prueba_treponemica',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA TREPONEMICA.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 17,
                    ],
                    'materialized' => true,
                ],
                'prueba_rapida_vih' => [
                    'label' => 'Prueba rapida VIH',
                    'short_label' => 'VIH',
                    'description' => 'Prueba rapida de VIH segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-emerald',
                    'cache_module_key' => 'prueba_rapida_vih',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA RAPIDA DE VIH.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 17,
                    ],
                    'materialized' => true,
                ],
                'hemoglobina' => [
                    'label' => 'Tamizaje de hemoglobina',
                    'short_label' => 'Hemoglobina',
                    'description' => 'Tamizaje de hemoglobina en poblacion de 12 a 13 anos.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-rose',
                    'cache_module_key' => 'hemoglobina',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE DE HEMOGLOBINA.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 13,
                    ],
                    'materialized' => true,
                ],
                'hematocrito' => [
                    'label' => 'Tamizaje de hematocrito',
                    'short_label' => 'Hematocrito',
                    'description' => 'Tamizaje de hematocrito en poblacion de 12 a 13 anos.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-violet',
                    'cache_module_key' => 'hematocrito',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE DE HEMATOCRITO.sql',
                    'filters' => [
                        'age_year_min' => 12,
                        'age_year_max' => 13,
                    ],
                    'materialized' => true,
                ],
                'alertas' => [
                    'label' => 'Alertas',
                    'short_label' => 'Alertas',
                    'description' => 'Pacientes con atenciones pendientes segun ventanas y curso de vida.',
                    'icon' => 'fas fa-bell',
                    'theme' => 'grad-orange',
                    'route' => 'ciclosvida.module.info',
                    'route_params' => ['slug' => 'adolescencia', 'moduleKey' => 'alertas'],
                    'record_type' => 'alert',
                    'materialized' => false,
                ],
                'datos_generales' => [
                    'label' => 'Datos generales',
                    'short_label' => 'Datos generales',
                    'description' => 'Resumen operativo del curso de vida y consolidado por modulo.',
                    'icon' => 'fas fa-chart-bar',
                    'theme' => 'grad-violet',
                    'route' => 'ciclosvida.module.info',
                    'route_params' => ['slug' => 'adolescencia', 'moduleKey' => 'datos_generales'],
                    'materialized' => false,
                ],
            ],
        ],
        'juventud' => [
            'slug' => 'juventud',
            'label' => 'Juventud',
            'menu_route' => 'ciclosvida.juventud.menu',
            'description' => 'De 18 a 28 anos. Enfasis en proyecto de vida, salud mental, SSR y riesgos cardiometabolicos.',
            'age_label' => '18 a 28 anos',
            'color' => 'bg-warning',
            'icon' => 'fas fa-user-graduate',
            'refresh' => ['days' => 120],
            'groups' => [
                [
                    'title' => 'Atenciones integrales',
                    'icon' => 'fas fa-stethoscope',
                    'items' => ['medica', 'salud_bucal'],
                ],
                [
                    'title' => 'Proteccion especifica',
                    'icon' => 'fas fa-shield-heart',
                    'items' => ['placa', 'detartraje', 'riesgo_cardiometabolico', 'r202_juventud'],
                ],
                [
                    'title' => 'Tamizajes de cuello uterino',
                    'icon' => 'fas fa-female',
                    'items' => ['citologia_cuello_uterino', 'inspeccion_cuello_uterino', 'adn_vph'],
                ],
                [
                    'title' => 'Salud sexual y reproductiva',
                    'icon' => 'fas fa-venus-mars',
                    'items' => [
                        'asesoria_anticoncepcion',
                        'planificacion_r202',
                        'prueba_treponemica',
                        'prueba_rapida_vih',
                        'prueba_rapida_hepatitis_b',
                        'prueba_rapida_hepatitis_c',
                    ],
                ],
                [
                    'title' => 'Gestion del riesgo',
                    'icon' => 'fas fa-clipboard-check',
                    'items' => ['alertas'],
                ],
            ],
            'modules' => [
                'medica' => [
                    'label' => 'Atencion en salud medica',
                    'short_label' => 'Medica',
                    'description' => 'Consulta medica para el curso de 18 a 28 anos.',
                    'icon' => 'fas fa-user-md',
                    'theme' => 'grad-indigo',
                    'cache_module_key' => 'medica',
                    'record_type' => 'event',
                    'sql_file' => 'MEDICINA.sql',
                    'filters' => [
                        'age_year_min' => 18,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'salud_bucal' => [
                    'label' => 'Atencion por odontologia',
                    'short_label' => 'Bucal',
                    'description' => 'Consulta odontologica con frecuencia de una vez cada 2 anos.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-sky',
                    'cache_module_key' => 'salud_bucal',
                    'record_type' => 'event',
                    'sql_file' => 'ODONTOLOGIA.sql',
                    'filters' => [
                        'age_year_min' => 18,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'placa' => [
                    'label' => 'Placa',
                    'short_label' => 'Placa',
                    'description' => 'Control de placa segun esquema.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'placa',
                    'record_type' => 'event',
                    'sql_file' => 'PLACA.sql',
                    'filters' => [
                        'age_year_min' => 18,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'detartraje' => [
                    'label' => 'Detartraje',
                    'short_label' => 'Detartraje',
                    'description' => 'Detartraje segun necesidad.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-amber',
                    'cache_module_key' => 'detartraje',
                    'record_type' => 'event',
                    'sql_file' => 'DETARTRAJE.sql',
                    'filters' => [
                        'age_year_min' => 18,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'riesgo_cardiometabolico' => [
                    'label' => 'Riesgo cardiovascular',
                    'short_label' => 'Riesgo CV',
                    'description' => 'Tamizaje cardiovascular con frecuencia operativa cada 5 anos.',
                    'icon' => 'fas fa-heartbeat',
                    'theme' => 'grad-orange',
                    'cache_module_key' => 'riesgo_cardiometabolico',
                    'record_type' => 'event',
                    'sql_file' => 'RIESGO CARDIVASCULAR Y METABOLICO - 114 - 456.sql',
                    'filters' => [
                        'age_year_min' => 18,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'r202_juventud' => [
                    'label' => 'R202',
                    'short_label' => 'R202',
                    'description' => 'Variables operativas R202 del curso de juventud.',
                    'icon' => 'fas fa-clipboard-list',
                    'theme' => 'grad-violet',
                    'cache_module_key' => 'r202_juventud',
                    'record_type' => 'event',
                    'sql_file' => 'R202 - JUVENTUD.sql',
                    'filters' => [
                        'age_year_min' => 18,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'citologia_cuello_uterino' => [
                    'label' => 'Citologia cuello uterino',
                    'short_label' => 'Citologia',
                    'description' => 'Citologia de cuello uterino a partir de los 20 anos.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-rose',
                    'cache_module_key' => 'citologia_cuello_uterino',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CUELLO UTERINO..sql',
                    'filters' => [
                        'age_year_min' => 20,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'inspeccion_cuello_uterino' => [
                    'label' => 'Inspeccion cuello uterino',
                    'short_label' => 'Inspeccion',
                    'description' => 'Inspeccion de cuello uterino a partir de los 20 anos.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-cyan',
                    'cache_module_key' => 'inspeccion_cuello_uterino',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CUELLO UTERINO. - INSPECCION.sql',
                    'filters' => [
                        'age_year_min' => 20,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'adn_vph' => [
                    'label' => 'ADN VPH',
                    'short_label' => 'ADN VPH',
                    'description' => 'Tamizaje por ADN VPH a partir de los 20 anos.',
                    'icon' => 'fas fa-dna',
                    'theme' => 'grad-emerald',
                    'cache_module_key' => 'adn_vph',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CUELLO UTERINO - ADN VPH.sql',
                    'filters' => [
                        'age_year_min' => 20,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'asesoria_anticoncepcion' => [
                    'label' => 'Asesoria en anticoncepcion',
                    'short_label' => 'Anticoncepcion',
                    'description' => 'Asesoria en anticoncepcion segun necesidad.',
                    'icon' => 'fas fa-venus-mars',
                    'theme' => 'grad-rose',
                    'cache_module_key' => 'asesoria_anticoncepcion',
                    'record_type' => 'event',
                    'sql_file' => 'ASESORIA ANTICONCEPCION.sql',
                    'filters' => [
                        'age_year_min' => 18,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'planificacion_r202' => [
                    'label' => 'Metodo de planificacion R202',
                    'short_label' => 'Planificacion R202',
                    'description' => 'Suministro o seguimiento del metodo de planificacion en R202.',
                    'icon' => 'fas fa-notes-medical',
                    'theme' => 'grad-violet',
                    'cache_module_key' => 'planificacion_r202',
                    'record_type' => 'event',
                    'sql_file' => 'PLANIFICACION_FAMILIAR_202.sql',
                    'filters' => [
                        'age_year_min' => 18,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'prueba_treponemica' => [
                    'label' => 'Prueba treponemica',
                    'short_label' => 'Treponemica',
                    'description' => 'Prueba treponemica segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'prueba_treponemica',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA TREPONEMICA.sql',
                    'filters' => [
                        'age_year_min' => 18,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'prueba_rapida_vih' => [
                    'label' => 'Prueba rapida VIH',
                    'short_label' => 'VIH',
                    'description' => 'Prueba rapida VIH segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-indigo',
                    'cache_module_key' => 'prueba_rapida_vih',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA RAPIDA DE VIH.sql',
                    'filters' => [
                        'age_year_min' => 18,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'prueba_rapida_hepatitis_b' => [
                    'label' => 'Prueba rapida hepatitis B',
                    'short_label' => 'Hepatitis B',
                    'description' => 'Prueba rapida de hepatitis B segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-amber',
                    'cache_module_key' => 'prueba_rapida_hepatitis_b',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA RAPIDA DE  Hepatitis B.sql',
                    'filters' => [
                        'age_year_min' => 18,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'prueba_rapida_hepatitis_c' => [
                    'label' => 'Prueba rapida hepatitis C',
                    'short_label' => 'Hepatitis C',
                    'description' => 'Prueba rapida de hepatitis C segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'prueba_rapida_hepatitis_c',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA RAPIDA DE  Hepatitis C.sql',
                    'filters' => [
                        'age_year_min' => 18,
                        'age_year_max' => 28,
                    ],
                    'materialized' => true,
                ],
                'alertas' => [
                    'label' => 'Alertas',
                    'short_label' => 'Alertas',
                    'description' => 'Pacientes con atenciones pendientes segun ventanas y curso de vida.',
                    'icon' => 'fas fa-bell',
                    'theme' => 'grad-orange',
                    'route' => 'ciclosvida.module.info',
                    'route_params' => ['slug' => 'juventud', 'moduleKey' => 'alertas'],
                    'record_type' => 'alert',
                    'materialized' => false,
                ],
                'datos_generales' => [
                    'label' => 'Datos generales',
                    'short_label' => 'Datos generales',
                    'description' => 'Resumen operativo del curso de vida y consolidado por modulo.',
                    'icon' => 'fas fa-chart-bar',
                    'theme' => 'grad-violet',
                    'route' => 'ciclosvida.module.info',
                    'route_params' => ['slug' => 'juventud', 'moduleKey' => 'datos_generales'],
                    'materialized' => false,
                ],
            ],
        ],
        'adultez' => [
            'slug' => 'adultez',
            'label' => 'Adultez',
            'menu_route' => 'ciclosvida.adultez.menu',
            'description' => 'De 29 a 59 anos. Prioriza riesgo cardiometabolico, salud mental, SSR y tamizajes.',
            'age_label' => '29 a 59 anos',
            'color' => 'bg-danger',
            'icon' => 'fas fa-user-tie',
            'refresh' => ['days' => 120],
            'groups' => [
                [
                    'title' => 'Atenciones integrales',
                    'icon' => 'fas fa-stethoscope',
                    'items' => ['medica', 'salud_bucal'],
                ],
                [
                    'title' => 'Odontologia y riesgo cardiovascular',
                    'icon' => 'fas fa-clipboard-check',
                    'items' => ['placa', 'detartraje', 'riesgo_cardiometabolico', 'r202_adultez'],
                ],
                [
                    'title' => 'Cuello uterino',
                    'icon' => 'fas fa-female',
                    'items' => ['citologia_cuello_uterino', 'adn_vph', 'inspeccion_cuello_uterino'],
                ],
                [
                    'title' => 'Otros tamizajes',
                    'icon' => 'fas fa-microscope',
                    'items' => ['mamografia', 'psa', 'tacto_rectal', 'tamizaje_colon'],
                ],
                [
                    'title' => 'Salud sexual y reproductiva',
                    'icon' => 'fas fa-venus-mars',
                    'items' => [
                        'asesoria_anticoncepcion',
                        'metodo_planificacion',
                        'r202_ssr',
                        'prueba_treponemica',
                        'prueba_rapida_vih',
                        'prueba_rapida_hepatitis_b',
                        'prueba_rapida_hepatitis_c',
                    ],
                ],
                [
                    'title' => 'Gestion del riesgo',
                    'icon' => 'fas fa-chart-line',
                    'items' => ['alertas'],
                ],
            ],
            'modules' => [
                'medica' => [
                    'label' => 'Atencion en salud medica',
                    'short_label' => 'Medica',
                    'description' => 'Consulta medica en los tramos de 29 a 59 anos.',
                    'icon' => 'fas fa-user-md',
                    'theme' => 'grad-indigo',
                    'cache_module_key' => 'medica',
                    'record_type' => 'event',
                    'sql_file' => 'MEDICINA.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'salud_bucal' => [
                    'label' => 'Atencion por odontologia',
                    'short_label' => 'Bucal',
                    'description' => 'Consulta odontologica con frecuencia operativa de una vez cada 2 anos.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-sky',
                    'cache_module_key' => 'salud_bucal',
                    'record_type' => 'event',
                    'sql_file' => 'ODONTOLOGIA.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'placa' => [
                    'label' => 'Placa',
                    'short_label' => 'Placa',
                    'description' => 'Control de placa, 1 vez cada 2 anos entre 29 y 59 anos.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'placa',
                    'record_type' => 'event',
                    'sql_file' => 'PLACA.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'detartraje' => [
                    'label' => 'Detartraje',
                    'short_label' => 'Detartraje',
                    'description' => 'Detartraje segun necesidad.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-amber',
                    'cache_module_key' => 'detartraje',
                    'record_type' => 'event',
                    'sql_file' => 'DETARTRAJE.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'riesgo_cardiometabolico' => [
                    'label' => 'Riesgo cardiovascular',
                    'short_label' => 'Riesgo CV',
                    'description' => 'Tamizaje cardiovascular con frecuencia operativa cada 5 anos.',
                    'icon' => 'fas fa-heartbeat',
                    'theme' => 'grad-amber',
                    'cache_module_key' => 'riesgo_cardiometabolico',
                    'record_type' => 'event',
                    'sql_file' => 'RIESGO CARDIVASCULAR Y METABOLICO - 114 - 456.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'r202_adultez' => [
                    'label' => 'R202 cardiovascular',
                    'short_label' => 'R202',
                    'description' => 'Variables operativas R202 del curso de adultez.',
                    'icon' => 'fas fa-clipboard-list',
                    'theme' => 'grad-violet',
                    'cache_module_key' => 'r202_adultez',
                    'record_type' => 'event',
                    'sql_file' => 'R202 - ADULTEZ.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'citologia_cuello_uterino' => [
                    'label' => 'Citologia cuello uterino',
                    'short_label' => 'Citologia',
                    'description' => 'Citologia de cuello uterino segun esquema.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-rose',
                    'cache_module_key' => 'citologia_cuello_uterino',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CUELLO UTERINO..sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'adn_vph' => [
                    'label' => 'ADN VPH',
                    'short_label' => 'ADN VPH',
                    'description' => 'ADN VPH a partir de los 30 anos.',
                    'icon' => 'fas fa-dna',
                    'theme' => 'grad-emerald',
                    'cache_module_key' => 'adn_vph',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CUELLO UTERINO - ADN VPH.sql',
                    'filters' => [
                        'age_year_min' => 30,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'inspeccion_cuello_uterino' => [
                    'label' => 'Inspeccion cuello uterino',
                    'short_label' => 'Inspeccion',
                    'description' => 'Inspeccion visual con acido acetico y lugol entre 30 y 50 anos.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-cyan',
                    'cache_module_key' => 'inspeccion_cuello_uterino',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CUELLO UTERINO. - INSPECCION.sql',
                    'filters' => [
                        'age_year_min' => 30,
                        'age_year_max' => 50,
                    ],
                    'materialized' => true,
                ],
                'mamografia' => [
                    'label' => 'Mamografia',
                    'short_label' => 'Mamografia',
                    'description' => 'Mamografia a partir de los 50 anos, cada 2 anos.',
                    'icon' => 'fas fa-x-ray',
                    'theme' => 'grad-rose',
                    'cache_module_key' => 'mamografia',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CANCER DE MAMA.sql',
                    'filters' => [
                        'age_year_min' => 50,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'psa' => [
                    'label' => 'PSA',
                    'short_label' => 'PSA',
                    'description' => 'PSA a partir de los 50 anos, cada 5 anos.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-indigo',
                    'cache_module_key' => 'psa',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CANCER DE PROSTATA.sql',
                    'filters' => [
                        'age_year_min' => 50,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'tacto_rectal' => [
                    'label' => 'Tacto rectal',
                    'short_label' => 'Tacto rectal',
                    'description' => 'Tacto rectal a partir de los 50 anos, cada 5 anos.',
                    'icon' => 'fas fa-stethoscope',
                    'theme' => 'grad-amber',
                    'cache_module_key' => 'tacto_rectal',
                    'record_type' => 'event',
                    'sql_file' => 'TACTO RECTAL.sql',
                    'filters' => [
                        'age_year_min' => 50,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'tamizaje_colon' => [
                    'label' => 'Sangre oculta en materia fecal',
                    'short_label' => 'Colon',
                    'description' => 'Tamizaje de colon cada 2 anos a partir de los 50 anos.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'tamizaje_colon',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CANCER DE COLON.sql',
                    'filters' => [
                        'age_year_min' => 50,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'asesoria_anticoncepcion' => [
                    'label' => 'Asesoria en anticoncepcion',
                    'short_label' => 'Anticoncepcion',
                    'description' => 'Asesoria en anticoncepcion segun necesidad.',
                    'icon' => 'fas fa-venus-mars',
                    'theme' => 'grad-rose',
                    'cache_module_key' => 'asesoria_anticoncepcion',
                    'record_type' => 'event',
                    'sql_file' => 'ASESORIA ANTICONCEPCION.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'metodo_planificacion' => [
                    'label' => 'Metodo de planificacion',
                    'short_label' => 'Planificacion',
                    'description' => 'Metodo de planificacion segun necesidad.',
                    'icon' => 'fas fa-notes-medical',
                    'theme' => 'grad-violet',
                    'cache_module_key' => 'metodo_planificacion',
                    'record_type' => 'event',
                    'sql_file' => 'PLANIFICACION_FAMILIAR_202.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'r202_ssr' => [
                    'label' => 'R202 SSR',
                    'short_label' => 'R202 SSR',
                    'description' => 'Variables R202 de salud sexual y reproductiva.',
                    'icon' => 'fas fa-clipboard-list',
                    'theme' => 'grad-emerald',
                    'cache_module_key' => 'r202_ssr',
                    'record_type' => 'event',
                    'sql_file' => 'R202 - ADULTEZ.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'prueba_treponemica' => [
                    'label' => 'Prueba treponemica',
                    'short_label' => 'Treponemica',
                    'description' => 'Prueba treponemica segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'prueba_treponemica',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA TREPONEMICA.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'prueba_rapida_vih' => [
                    'label' => 'Prueba rapida VIH',
                    'short_label' => 'VIH',
                    'description' => 'Prueba rapida VIH segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-indigo',
                    'cache_module_key' => 'prueba_rapida_vih',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA RAPIDA DE VIH.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'prueba_rapida_hepatitis_b' => [
                    'label' => 'Prueba rapida hepatitis B',
                    'short_label' => 'Hepatitis B',
                    'description' => 'Prueba rapida de hepatitis B segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-amber',
                    'cache_module_key' => 'prueba_rapida_hepatitis_b',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA RAPIDA DE  Hepatitis B.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'prueba_rapida_hepatitis_c' => [
                    'label' => 'Prueba rapida hepatitis C',
                    'short_label' => 'Hepatitis C',
                    'description' => 'Prueba rapida de hepatitis C segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'prueba_rapida_hepatitis_c',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA RAPIDA DE  Hepatitis C.sql',
                    'filters' => [
                        'age_year_min' => 29,
                        'age_year_max' => 59,
                    ],
                    'materialized' => true,
                ],
                'alertas' => [
                    'label' => 'Alertas',
                    'short_label' => 'Alertas',
                    'description' => 'Pacientes con atenciones pendientes segun ventanas y curso de vida.',
                    'icon' => 'fas fa-bell',
                    'theme' => 'grad-orange',
                    'route' => 'ciclosvida.module.info',
                    'route_params' => ['slug' => 'adultez', 'moduleKey' => 'alertas'],
                    'record_type' => 'alert',
                    'materialized' => false,
                ],
                'datos_generales' => [
                    'label' => 'Datos generales',
                    'short_label' => 'Datos generales',
                    'description' => 'Resumen operativo del curso de vida y consolidado por modulo.',
                    'icon' => 'fas fa-chart-bar',
                    'theme' => 'grad-violet',
                    'route' => 'ciclosvida.module.info',
                    'route_params' => ['slug' => 'adultez', 'moduleKey' => 'datos_generales'],
                    'materialized' => false,
                ],
            ],
        ],
        'vejez' => [
            'slug' => 'vejez',
            'menu_route' => 'ciclosvida.vejez.menu',
            'label' => 'Vejez',
            'description' => 'De 60 anos y mas. Enfoque en funcionalidad, fragilidad, riesgo cronico y cuidado integral.',
            'age_label' => '60 anos y mas',
            'color' => 'bg-teal',
            'icon' => 'fas fa-blind',
            'refresh' => ['days' => 120],
            'groups' => [
                [
                    'title' => 'Atenciones integrales',
                    'icon' => 'fas fa-stethoscope',
                    'items' => ['medica', 'salud_bucal'],
                ],
                [
                    'title' => 'Odontologia y riesgo cardiovascular',
                    'icon' => 'fas fa-tooth',
                    'items' => ['placa', 'detartraje', 'riesgo_cardiometabolico', 'r202_vejez'],
                ],
                [
                    'title' => 'Tamizajes',
                    'icon' => 'fas fa-microscope',
                    'items' => ['citologia_cuello_uterino', 'mamografia', 'psa', 'tacto_rectal', 'tamizaje_colon'],
                ],
                [
                    'title' => 'Proteccion especifica / R202',
                    'icon' => 'fas fa-clipboard-list',
                    'items' => [
                        'asesoria_anticoncepcion',
                        'metodo_planificacion',
                        'r202_ssr',
                        'prueba_treponemica',
                        'prueba_rapida_vih',
                        'prueba_rapida_hepatitis_b',
                        'prueba_rapida_hepatitis_c',
                    ],
                ],
                [
                    'title' => 'Gestion del riesgo',
                    'icon' => 'fas fa-chart-line',
                    'items' => ['alertas'],
                ],
            ],
            'modules' => [
                'medica' => [
                    'label' => 'Atencion en salud medica',
                    'short_label' => 'Medica',
                    'description' => 'Consulta medica con seguimiento operativo por tramos de 3 anos desde los 60.',
                    'icon' => 'fas fa-user-md',
                    'theme' => 'grad-indigo',
                    'cache_module_key' => 'medica',
                    'record_type' => 'event',
                    'sql_file' => 'MEDICINA.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'salud_bucal' => [
                    'label' => 'Atencion por odontologia',
                    'short_label' => 'Bucal',
                    'description' => 'Consulta odontologica con frecuencia operativa de una vez cada 2 anos.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-sky',
                    'cache_module_key' => 'salud_bucal',
                    'record_type' => 'event',
                    'sql_file' => 'ODONTOLOGIA.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'placa' => [
                    'label' => 'Placa',
                    'short_label' => 'Placa',
                    'description' => 'Control de placa 1 vez cada 2 anos.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'placa',
                    'record_type' => 'event',
                    'sql_file' => 'PLACA.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'detartraje' => [
                    'label' => 'Detartraje',
                    'short_label' => 'Detartraje',
                    'description' => 'Detartraje segun necesidad.',
                    'icon' => 'fas fa-tooth',
                    'theme' => 'grad-amber',
                    'cache_module_key' => 'detartraje',
                    'record_type' => 'event',
                    'sql_file' => 'DETARTRAJE.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'riesgo_cardiometabolico' => [
                    'label' => 'Riesgo cardiovascular',
                    'short_label' => 'Riesgo CV',
                    'description' => 'Tamizaje cardiovascular con frecuencia operativa cada 5 anos.',
                    'icon' => 'fas fa-heartbeat',
                    'theme' => 'grad-orange',
                    'cache_module_key' => 'riesgo_cardiometabolico',
                    'record_type' => 'event',
                    'sql_file' => 'RIESGO CARDIVASCULAR Y METABOLICO - 114 - 456.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'r202_vejez' => [
                    'label' => 'R202',
                    'short_label' => 'R202',
                    'description' => 'Variables operativas R202 del curso de vejez.',
                    'icon' => 'fas fa-clipboard-list',
                    'theme' => 'grad-violet',
                    'cache_module_key' => 'r202_vejez',
                    'record_type' => 'event',
                    'sql_file' => 'R202 - VEJEZ.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'citologia_cuello_uterino' => [
                    'label' => 'Citologia cuello uterino',
                    'short_label' => 'Citologia',
                    'description' => 'Citologia hasta los 65 anos.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-rose',
                    'cache_module_key' => 'citologia_cuello_uterino',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CUELLO UTERINO..sql',
                    'filters' => [
                        'age_year_min' => 60,
                        'age_year_max' => 65,
                    ],
                    'materialized' => true,
                ],
                'mamografia' => [
                    'label' => 'Mamografia',
                    'short_label' => 'Mamografia',
                    'description' => 'Mamografia hasta los 69 anos, cada 2 anos.',
                    'icon' => 'fas fa-x-ray',
                    'theme' => 'grad-rose',
                    'cache_module_key' => 'mamografia',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CANCER DE MAMA.sql',
                    'filters' => [
                        'age_year_min' => 60,
                        'age_year_max' => 69,
                    ],
                    'materialized' => true,
                ],
                'psa' => [
                    'label' => 'PSA',
                    'short_label' => 'PSA',
                    'description' => 'PSA hasta los 75 anos, cada 5 anos.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-indigo',
                    'cache_module_key' => 'psa',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CANCER DE PROSTATA.sql',
                    'filters' => [
                        'age_year_min' => 60,
                        'age_year_max' => 75,
                    ],
                    'materialized' => true,
                ],
                'tacto_rectal' => [
                    'label' => 'Tacto rectal',
                    'short_label' => 'Tacto rectal',
                    'description' => 'Tacto rectal hasta los 75 anos, cada 5 anos.',
                    'icon' => 'fas fa-stethoscope',
                    'theme' => 'grad-amber',
                    'cache_module_key' => 'tacto_rectal',
                    'record_type' => 'event',
                    'sql_file' => 'TACTO RECTAL.sql',
                    'filters' => [
                        'age_year_min' => 60,
                        'age_year_max' => 75,
                    ],
                    'materialized' => true,
                ],
                'tamizaje_colon' => [
                    'label' => 'Sangre oculta en materia fecal',
                    'short_label' => 'Colon',
                    'description' => 'Tamizaje de colon hasta los 75 anos, cada 2 anos.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'tamizaje_colon',
                    'record_type' => 'event',
                    'sql_file' => 'TAMIZAJE CANCER DE COLON.sql',
                    'filters' => [
                        'age_year_min' => 60,
                        'age_year_max' => 75,
                    ],
                    'materialized' => true,
                ],
                'asesoria_anticoncepcion' => [
                    'label' => 'Asesoria en anticoncepcion',
                    'short_label' => 'Anticoncepcion',
                    'description' => 'Asesoria en anticoncepcion segun necesidad.',
                    'icon' => 'fas fa-venus-mars',
                    'theme' => 'grad-rose',
                    'cache_module_key' => 'asesoria_anticoncepcion',
                    'record_type' => 'event',
                    'sql_file' => 'ASESORIA ANTICONCEPCION.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'metodo_planificacion' => [
                    'label' => 'Metodo de planificacion',
                    'short_label' => 'Planificacion',
                    'description' => 'Metodo de planificacion segun necesidad.',
                    'icon' => 'fas fa-notes-medical',
                    'theme' => 'grad-violet',
                    'cache_module_key' => 'metodo_planificacion',
                    'record_type' => 'event',
                    'sql_file' => 'PLANIFICACION_FAMILIAR_202.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'r202_ssr' => [
                    'label' => 'R202 SSR',
                    'short_label' => 'R202 SSR',
                    'description' => 'Variables R202 de salud sexual y reproductiva.',
                    'icon' => 'fas fa-clipboard-list',
                    'theme' => 'grad-emerald',
                    'cache_module_key' => 'r202_ssr',
                    'record_type' => 'event',
                    'sql_file' => 'R202 - VEJEZ.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'prueba_treponemica' => [
                    'label' => 'Prueba treponemica',
                    'short_label' => 'Treponemica',
                    'description' => 'Prueba treponemica segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'prueba_treponemica',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA TREPONEMICA.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'prueba_rapida_vih' => [
                    'label' => 'Prueba rapida VIH',
                    'short_label' => 'VIH',
                    'description' => 'Prueba rapida VIH segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-indigo',
                    'cache_module_key' => 'prueba_rapida_vih',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA RAPIDA DE VIH.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'prueba_rapida_hepatitis_b' => [
                    'label' => 'Prueba rapida hepatitis B',
                    'short_label' => 'Hepatitis B',
                    'description' => 'Prueba rapida de hepatitis B segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-amber',
                    'cache_module_key' => 'prueba_rapida_hepatitis_b',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA RAPIDA DE  Hepatitis B.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'prueba_rapida_hepatitis_c' => [
                    'label' => 'Prueba rapida hepatitis C',
                    'short_label' => 'Hepatitis C',
                    'description' => 'Prueba rapida de hepatitis C segun necesidad.',
                    'icon' => 'fas fa-vial',
                    'theme' => 'grad-lime',
                    'cache_module_key' => 'prueba_rapida_hepatitis_c',
                    'record_type' => 'event',
                    'sql_file' => 'PRUEBA RAPIDA DE  Hepatitis C.sql',
                    'filters' => [
                        'age_year_min' => 60,
                    ],
                    'materialized' => true,
                ],
                'alertas' => [
                    'label' => 'Alertas',
                    'short_label' => 'Alertas',
                    'description' => 'Pacientes con atenciones pendientes segun ventanas y curso de vida.',
                    'icon' => 'fas fa-bell',
                    'theme' => 'grad-orange',
                    'route' => 'ciclosvida.module.info',
                    'route_params' => ['slug' => 'vejez', 'moduleKey' => 'alertas'],
                    'record_type' => 'alert',
                    'materialized' => false,
                ],
                'datos_generales' => [
                    'label' => 'Datos generales',
                    'short_label' => 'Datos generales',
                    'description' => 'Resumen operativo del curso de vida y consolidado por modulo.',
                    'icon' => 'fas fa-chart-bar',
                    'theme' => 'grad-violet',
                    'route' => 'ciclosvida.module.info',
                    'route_params' => ['slug' => 'vejez', 'moduleKey' => 'datos_generales'],
                    'materialized' => false,
                ],
            ],
        ],
    ],
];
